### ISSUE TITLE
Background animation for videos

### ISSUE THREAD

**Issue by justinsantoro** [justinsantoro/politeia-digest#1]
I am in need of a background animation that fits with the images richardred is using for the digest headers: 

![img](https://raw.githubusercontent.com/justinsantoro/politeia-digest-video/video/img/issue016/016-title.png)

relevant dcrdesign issues: 
- https://github.com/decred/dcrdesign/issues/113
- https://github.com/decred/dcrdesign/issues/134

This video as of now is just a test so anything similar to these images will work for now. If in the future  it is decided to continue this project we may need to coordinate with the design team.

a 1920x1080 looping animation is all that is needed. Be sure to use blues from the design guidelines: https://github.com/decred/dcrdesign/files/2160926/decred.-.visual.toolkit.-.0618.pdf

**Comment by aumi121** [comment]
Hi Justin,
I would like to work on it, if you have no issue.

**Comment by justinsantoro** [comment]
great. please post links here for review when ready.

**Comment by aumi121** [comment]
Sure, will update you once it is done. Thanks for this opportunity.

**Comment by aumi121** [comment]
[https://www.dropbox.com/s/7n0jxq3blpl06od/Comp%201_1.mp4?dl=0](url)
For better quality, please download it first. I will send one more version using particles.

**Comment by justinsantoro** [comment]
very cool. looking forward to seeing the next one.

**Comment by aumi121** [comment]
There were some changes left so that is why I am sharing the rest of versions now. These versions are based on the following link
[https://decred.org/contributors/](url) 

Version 2.0 : [https://www.dropbox.com/s/fjcy1775i3kkawg/Comp%204.mp4?dl=0](url)
Version 2.1 : [https://www.dropbox.com/s/zgv6kiahndhcm5i/Comp%203.mp4?dl=0](url)
Version 2.3 : [https://www.dropbox.com/s/kifsoo3ditas2ml/Comp%202.mp4?dl=0](url)

**Comment by justinsantoro** [comment]
We will go with the first one since its closest to images used in the text digests. The others version 2.1 and 2.3 are probably too colorful. 2.0 being closest to the ones on the site is best. Would look nice as a background used in a developer tutorial.

**Comment by aumi121** [comment]
Thanks for the feedback and I totally get your points.
